version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: lbaas-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:

