---
- name: Deploy F5 AS3 Configuration (Mock)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    as3_json_payload: "{}" # Default to an empty JSON object
    output_log_path: "/tmp/f5_as3_deployment_log.txt"

  tasks:
    - name: Validate AS3 JSON Payload (Basic Check)
      ansible.builtin.assert:
        that:
          - as3_json_payload | from_json # Check if it's valid JSON
        fail_msg: "Provided as3_json_payload is not valid JSON."
        success_msg: "AS3 JSON payload is valid."

    - name: Log AS3 JSON Payload to a file (Simulating Deployment)
      ansible.builtin.copy:
        content: "{{ as3_json_payload | to_nice_json }}"
        dest: "{{ output_log_path }}"
      notify: Display deployment log path

    - name: Display AS3 JSON Payload (Debug)
      ansible.builtin.debug:
        msg: "Simulating deployment of AS3 JSON: {{ as3_json_payload | to_nice_json }}"

  handlers:
    - name: Display deployment log path
      ansible.builtin.debug:
        msg: "Mock F5 AS3 deployment logged to: {{ output_log_path }}"

